# Generated by Django 4.0.4 on 2022-06-25 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0008_delete_admininterfacetheme_delete_authgroup_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminInterfaceTheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('active', models.IntegerField()),
                ('title', models.CharField(max_length=50)),
                ('title_visible', models.IntegerField()),
                ('logo', models.CharField(max_length=100)),
                ('logo_visible', models.IntegerField()),
                ('css_header_background_color', models.CharField(max_length=10)),
                ('title_color', models.CharField(max_length=10)),
                ('css_header_text_color', models.CharField(max_length=10)),
                ('css_header_link_color', models.CharField(max_length=10)),
                ('css_header_link_hover_color', models.CharField(max_length=10)),
                ('css_module_background_color', models.CharField(max_length=10)),
                ('css_module_text_color', models.CharField(max_length=10)),
                ('css_module_link_color', models.CharField(max_length=10)),
                ('css_module_link_hover_color', models.CharField(max_length=10)),
                ('css_module_rounded_corners', models.IntegerField()),
                ('css_generic_link_color', models.CharField(max_length=10)),
                ('css_generic_link_hover_color', models.CharField(max_length=10)),
                ('css_save_button_background_color', models.CharField(max_length=10)),
                ('css_save_button_background_hover_color', models.CharField(max_length=10)),
                ('css_save_button_text_color', models.CharField(max_length=10)),
                ('css_delete_button_background_color', models.CharField(max_length=10)),
                ('css_delete_button_background_hover_color', models.CharField(max_length=10)),
                ('css_delete_button_text_color', models.CharField(max_length=10)),
                ('list_filter_dropdown', models.IntegerField()),
                ('related_modal_active', models.IntegerField()),
                ('related_modal_background_color', models.CharField(max_length=10)),
                ('related_modal_rounded_corners', models.IntegerField()),
                ('logo_color', models.CharField(max_length=10)),
                ('recent_actions_visible', models.IntegerField()),
                ('favicon', models.CharField(max_length=100)),
                ('related_modal_background_opacity', models.CharField(max_length=5)),
                ('env_name', models.CharField(max_length=50)),
                ('env_visible_in_header', models.IntegerField()),
                ('env_color', models.CharField(max_length=10)),
                ('env_visible_in_favicon', models.IntegerField()),
                ('related_modal_close_button_visible', models.IntegerField()),
                ('language_chooser_active', models.IntegerField()),
                ('language_chooser_display', models.CharField(max_length=10)),
                ('list_filter_sticky', models.IntegerField()),
                ('form_pagination_sticky', models.IntegerField()),
                ('form_submit_sticky', models.IntegerField()),
                ('css_module_background_selected_color', models.CharField(max_length=10)),
                ('css_module_link_selected_color', models.CharField(max_length=10)),
                ('logo_max_height', models.PositiveSmallIntegerField()),
                ('logo_max_width', models.PositiveSmallIntegerField()),
                ('foldable_apps', models.IntegerField()),
            ],
            options={
                'db_table': 'admin_interface_theme',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.IntegerField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.IntegerField()),
                ('is_active', models.IntegerField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.PositiveSmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
    ]
